# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-react-boilerplate

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**    

provider:
  name: aws
  runtime: nodejs4.3
  region: ${self:custom.writeEnvVars.REGION}
  stage: ${self:custom.writeEnvVars.STAGE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*"

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-write-env-vars

custom:
  writeEnvVars: ${file(./env.yml)}
  stage: ${opt:stage, self:custom.writeEnvVars.STAGE}
  authorizer:
    arn: arn:aws:lambda:${self:provider.region}:${self:custom.writeEnvVars.AWS_ACCOUNT_ID}:function:serverless-authentication-${self:custom.stage}-authorize
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization
    identityValidationExpression: .*
  dynamodb:
    start:
      migration: true
    migration:
      dir: offline/migrations
      table_prefix: ${self:custom.stage}

functions:
  todo:
    handler: handlers/todo/handler.todo
    events:
      - http:
          method: GET
          path: todos/{userId}/register          
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
          authorizer: ${self:custom.authorizer}

      - http:
          method: GET
          path: todos/{userId}/getAll          
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
          authorizer: ${self:custom.authorizer}

      - http:
          method: DELETE
          path: todos/{userId}/delete/{id}
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
          authorizer: ${self:custom.authorizer}

      - http:
          method: POST
          path: todos/{userId}/create
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
          authorizer: ${self:custom.authorizer}

      - http:
          method: PUT
          path: todos/{userId}/update
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
          authorizer: ${self:custom.authorizer}

      - http:
          method: PUT
          path: todos/{userId}/status
          integration: lambda
          cors: true
          request: ${file(./templates.yml):request}
          authorizer: ${self:custom.authorizer}

resources:
  Resources:
    Dynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: todoDate
          AttributeType: S
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
        LocalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoDate
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.stage}-todos
