events:
  - http:
      method: GET
      path: todos
      cors: true
      authorizer: authorizerFunc
      request: ${file(./templates.yml):request}

  - http:
      method: GET
      path: todos/{id}
      cors: true
      authorizer: authorizerFunc
      request: ${file(./templates.yml):request}

  - http:
      method: POST
      path: todos
      cors: true
      authorizer: authorizerFunc
      request: ${file(./templates.yml):request}

  - http:
      method: PUT
      path: todos/{id}
      cors: true
      authorizer: authorizerFunc
      request: ${file(./templates.yml):request}
